# Generated by Django 5.0 on 2024-05-28 03:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendemail',
            name='id',
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
